# # POST https://mattallen.tech/list-app/register HTTP/1.1
# POST http://localhost:8080/list-app/register HTTP/1.1
# content-type: application/json

# {
#     "user": {
#         "name": "Demo User",
#         "email": "demo@demo.com",
#         "password": "Test12345!"
#     }
# }

# POST http://localhost:8080/list-app/login HTTP/1.1
# content-type: application/json

# {
#     "email": "demo@demo.com",
#     "password": "Test12345!"
# }

POST http://localhost:8080/list-app/token HTTP/1.1
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkRlbW8gVXNlciIsImVtYWlsIjoiZGVtb0BkZW1vLmNvbSIsImlhdCI6MTY2MzUzMTc2OH0.snI2x8Y94KW62aW5T91vnLfL_EnIP56Hmt3IbySkkGk"
}

# POST http://localhost:8080/list-app/logout HTTP/1.1
# content-type: application/json

# {
#     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkRlbW8gVXNlciIsImVtYWlsIjoiZGVtb0BkZW1vLmNvbSIsImlhdCI6MTY2MzUzMTc2OH0.snI2x8Y94KW62aW5T91vnLfL_EnIP56Hmt3IbySkkGk"
# }


# POST http://localhost:8080/list-app/create-list HTTP/1.1
# //POST https://mattallen.tech/list-app/create-list HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkRlbW8gVXNlciIsImVtYWlsIjoiZGVtb0BkZW1vLmNvbSIsImlhdCI6MTY2MDIyNzE0MywiZXhwIjoxNjYwMjM3MTQzfQ.qp-2ZPekmeLiRALmWw9ZOZclRJpYKvY8RqssmYucYyI

# {
#     "listTitle": "Matt's list"
# }

# GET http://localhost:8080/list-app/get-lists HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkRlbW8gVXNlciIsImVtYWlsIjoiZGVtb0BkZW1vLmNvbSIsImlhdCI6MTY2MzUzMTg5NiwiZXhwIjoxNjYzNTMyNDk2fQ.2sR2nvVpPp1k6J0wAlEv_42QvSNF9mTXi1s_UhuO3Ew

# POST http://lostalhost:8080/list-app/token HTTP/1.1
# Content-Type: application/json
# {"token": "12345"}

# POST http://localhost:8080/list-app/add-List-item HTTP/1.1
# POST https://mattallen.tech/list-app/add-List-item HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im1hdHQiLCJlbWFpbCI6Im1hdHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODg5OTA0LCJleHAiOjE2NTk4OTk5MDR9.Q714honuV66lbo-tUjtiWvAzr_Z4Z7LoOR2n-ooSgTI

# {
#     "listID": "1",
#     "listItem": "go shopping"
# }

#  POST http://localhost:8080/list-app/delete-List-item HTTP/1.1
#  POST https://mattallen.tech/list-app/delete-List-item HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im1hdHQiLCJlbWFpbCI6Im1hdHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODg5OTA0LCJleHAiOjE2NTk4OTk5MDR9.Q714honuV66lbo-tUjtiWvAzr_Z4Z7LoOR2n-ooSgTI

# {
#     "listID": "46",
#     "listItem": "go shopping"
# }

# POST http://localhost:8080/list-app/delete-list HTTP/1.1
# POST https://mattallen.tech/list-app/delete-list HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im1hdHQiLCJlbWFpbCI6Im1hdHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODkxMjg2LCJleHAiOjE2NTk5MDEyODZ9.6q38PhQexyTvXqgs4Gdgrm__X-jYJZdxqS1aE3SiAtk

# {
#     "list": {
#         "id": "46",
#         "items": []
#     }
# }

# GET https://mattallen.tech/list-app/get-lists HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Im1hdHQiLCJlbWFpbCI6Im1hdHRAZ21haWwuY29tIiwiaWF0IjoxNjU5ODkxMjg2LCJleHAiOjE2NTk5MDEyODZ9.6q38PhQexyTvXqgs4Gdgrm__X-jYJZdxqS1aE3SiAtk
