# POST http://localhost:8080/list-app/register HTTP/1.1
# content-type: application/json

# {
#     "user": {
#         "name": "matt",
#         "email": "matt@gmail.com",
#         "password": "test12345"
#     }
# }

# POST http://localhost:8080/list-app/login HTTP/1.1
# content-type: application/json

# {
#     "username": "matt@gmail.com",
#     "password": "test12345"
# }

# POST http://localhost:8080/list-app/create-list HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJtYXR0IiwiZW1haWwiOiJtYXR0QGdtYWlsLmNvbSIsImlhdCI6MTY1OTgzODk2NCwiZXhwIjoxNjU5ODQ4OTY0fQ.gCiX1m0xUrVih7kCO0nYzmaC9-LXGVeB7PzpcqrI50s

# {
#     "listTitle": "Matt's list 3"
# }

# POST http://localhost:8080/list-app/delete-list HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJtYXR0IiwiZW1haWwiOiJtYXR0QGdtYWlsLmNvbSIsImlhdCI6MTY1OTgzODk2NCwiZXhwIjoxNjU5ODQ4OTY0fQ.gCiX1m0xUrVih7kCO0nYzmaC9-LXGVeB7PzpcqrI50s

# {
#     "list": {
#         "id": "43",
#         "items": ["do something"]
#     }
# }

# POST http://localhost:8080/list-app/add-List-item HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJtYXR0IiwiZW1haWwiOiJtYXR0QGdtYWlsLmNvbSIsImlhdCI6MTY1OTgzODk2NCwiZXhwIjoxNjU5ODQ4OTY0fQ.gCiX1m0xUrVih7kCO0nYzmaC9-LXGVeB7PzpcqrI50s

# {
#     "listID": "43",
#     "listItem": "go shopping"
# }

 POST http://localhost:8080/list-app/delete-List-item HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJtYXR0IiwiZW1haWwiOiJtYXR0QGdtYWlsLmNvbSIsImlhdCI6MTY1OTgzODk2NCwiZXhwIjoxNjU5ODQ4OTY0fQ.gCiX1m0xUrVih7kCO0nYzmaC9-LXGVeB7PzpcqrI50s

# {
#     "listID": "43",
#     "listItem": "go shopping"
# }

# GET http://localhost:8080/list-app/get-lists HTTP/1.1
# content-type: application/json
# Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsIm5hbWUiOiJtYXR0IiwiZW1haWwiOiJtYXR0QGdtYWlsLmNvbSIsImlhdCI6MTY1OTgzODk2NCwiZXhwIjoxNjU5ODQ4OTY0fQ.gCiX1m0xUrVih7kCO0nYzmaC9-LXGVeB7PzpcqrI50s
